apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
data:
  RETAIL_CATALOG_PERSISTENCE_USER: "Y2F0YWxvZw=="
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "c3VyZXNoZGIxMDE="

# ==================================
# To encode to base64 in pwsh
# [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("your_string_here"))

# To encode to base64 in bash(linux shell)
# echo -n "your_string_here" | base64

# ======================================

# To decode in pwsh
# [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("your_base64_string"))

# To decode in bash(linux shell)
# echo -n "your_base64_string" | base64 --decode